web:
  SHARE_API_URL: "/adminapi/chatgpt/"
  SHARE_ADDR : "https://xxx.com" # 更改为你的share地址
  SHARE_API_AUTH : "123456" 
  # 此部分无需修改
  SQLALCHEMY_DATABASE_URI: 'sqlite:///cockes.sqlite'
  SQLALCHEMY_TRACK_MODIFICATIONS: False
  JWT_TOKEN_LOCATION: ['headers']
  JWT_COOKIE_SECURE: True
  JWT_COOKIE_CSRF_PROTECT: False
  REDIS_HOST: 'redis'
  REDIS_PORT: 6379
  REDIS_DB: 1
  REDIS_PASSWORD: ''
  
  SECRET_KEY : 'xxx' # 更换为一个强随机值
  SECURITY_PASSWORD_SALT : 'xxx'  # 更换为一个强随机值
  JWT_SECRET_KEY : 'xxx'  # 更换为一个强随机值
  
  JWT_ACCESS_TOKEN_EXPIRES : 50400  # JWT 访问令牌有效期（单位：秒），例如3600秒（1小时）
  CHAR_SET : ['0', '1', '2', '3', '4', '5', '6', '7', '8', '9',
              'a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j', 'k', 'l', 'm',
              'n', 'o', 'p', 'q', 'r', 's', 't', 'u', 'v', 'w', 'x', 'y', 'z',
              'A', 'B', 'C', 'D', 'E', 'F', 'G', 'H', 'I', 'J', 'K', 'L', 'M',
              'N', 'O', 'P', 'Q', 'R', 'S', 'T', 'U', 'V', 'W', 'X', 'Y', 'Z']

database:
  default: # 数据源名称,当不指定数据源时 default 为默认数据源
    type: "mysql" # 数据库类型
    host: "mysql" # 数据库地址
    port: "3306" # 数据库端口
    user: "root" # 数据库用户名
    pass: "123456" # 数据库密码
    name: "cool" # 数据库名称
    charset: "utf8mb4" # 数据库编码
    timezone: "Asia/Shanghai" # 数据库时区
    # debug: true # 是否开启调试模式，开启后会打印SQL日志
    createdAt: "createTime" # 创建时间字段
    updatedAt: "updateTime" # 更新时间字段

redis:
  cool:
    address: "redis:6379"
    db: 0


cool:
  autoMigrate: true
  eps: true
  file:
    mode: "local"
    domain: "http://127.0.0.1:8300"

server:
    clientMaxBodySize:   810241024          # 客户端最大Body上传限制大小，影响文件上传大小(Byte)。默认为8*1024*1024=8MB

modules:
  base:
    jwt:
      sso: false
      secret: "chatgpt-share-server"
      token:
        expire: 7200 # 2*3600
        refreshExpire: 1296000 # 24*3600*15
    middleware:
      authority:
        enable: 1
      log:
        enable: 1

APIAUTH: 123456      
